### ISSUE TITLE
Error when setting up the additional custom bridges in noetic-devel branch

### ISSUE THREAD

**Issue by sergimolina** [LCAS/mqtt_bridge#22]
When I run the `demo.launch` in noetic, I get a warning while setting the DynamicBridgeServer, RemoteService and LocalServiceProxy saying:
`[INFO] [1673281065.122969]: MQTT connected for the first time, setting up bridges`
`[WARN] [1673281065.126565]: MQTT loop received exception, retrying: create_bridge() missing 3 required positional arguments: 'msg_type', 'topic_from', and 'topic_to'
`

I get also a warning when setting up PublishBridge , SubscribeBridge saying:
`SubscribeBridge: subscribe ROS topic /A/in to topic /A/out via MQTT __dynamic_server_DATA__A_in_TO__A_out`
`[WARN] [1673282494.836520]: MQTT loop received exception, retrying: can't serialize <class 'std_msgs.msg._String.String'>
`

**Comment by sergimolina** [comment]
Adding fake parameters to fulfill the exception (i.e.  msg_type', 'topic_from', and 'topic_to' ) throws another warning:
`[WARN] [1673440049.357235]: MQTT loop received exception, retrying: not enough values to unpack (expected 2, got 1)`

**Comment by sergimolina** [comment]
it seems that the type checking here: https://github.com/LCAS/mqtt_bridge/blob/noetic-devel/src/mqtt_bridge/bridge.py#L15 makes the additional custom bridges unsable.
I will create a new branch with the changes.

**Comment by marc-hanheide** [comment]
hopefully addressed in #24

**Comment by marc-hanheide** [comment]
please reopen if not fixed in #24
