### ISSUE TITLE
No more messages from rostopics after installing mqtt, even when not running it.

### ISSUE THREAD

**Issue by adambinch** [LCAS/mqtt_bridge#6]
Installed this version from source, and its dependencies, in order to run the multisim (from rasberry repo, toponav2-devel branch). Couldn't run the multisim in the end, had a bunch of errors, so shut it down with a view to trying it again later. Then ran a single robot sim using a tmule script that doesn't even run mqtt, but found that no messages were being published onto the toponav topics.

Fixed by removing mqtt-bridge from my workspace, and recompiling (scrapped my build and devel folder too but not sure if that was necessary).

**Comment by marc-hanheide** [comment]
I really can't see how mqtt could be responsible for that... I must assume this was a side-effect / coincidence. Let me know if you have any more evidence.
