### ISSUE TITLE
Missing run dependencies

### ISSUE THREAD

**Issue by magnucha** [LCAS/mqtt_bridge#9]
Missing declaration of the following python run dependencies raises errors when launching the node.
```
inject<4.0.0
paho-mqtt
msgpack-python
```

**Comment by marc-hanheide** [comment]
Ah, interesting...

how does this relate to https://github.com/LCAS/mqtt_bridge/blob/aefe2fe47e4413192d743fb3f4da5ed379d6692e/requirements.txt#L1-L4

? I thought it should defined already. Maybe just add a `pip install -r` in your docker?

**Comment by magnucha** [comment]
Ideally I wanted to have rosdep install them by setting this in package.xml, and using version tags like described in https://www.ros.org/reps/rep-0140.html#build-depend-multiple. But these don't actually seem to work, since `<exec_depend version_lt="4.0.0">python-inject-pip</exec_depend>` installs v4.3.1.

So I guess requirements.txt is the way for now :(
